### ISSUE TITLE
Move serverspec testing to be via ansible

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#101]
See these repos - 

https://github.com/volanja/ansible-sample-tdd
https://github.com/volanja/ansible_spec

**Comment by enxebre** [comment]
moving this to critical as we are not running serverspecs at all after provision since we moved to ansible

**Comment by wfindley** [comment]
Server spec tests?  I love you.

**Comment by asnaedae** [comment]
we love serverspec too!
