### ISSUE TITLE
Move marathon out to a docker container

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#105]
We should be able to move marathon to be a docker container - a la 

https://registry.hub.docker.com/u/mesosphere/marathon/

If we allow provisioning all frameworks via docker, this should make things more composable / pluggable.

**Comment by tayzlor** [comment]
Should be made an "Add-on", maybe similar to how these work https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons

**Comment by enxebre** [comment]
example using offcial comunity images https://github.com/sean-bennett112/mesos-docker/blob/master/fig.yml
