### ISSUE TITLE
Add a simple microservice example 

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#115]
Simple hello world microservice that can be deployed via marathon.

Could use something easy like spring boot / nodejs

**Comment by rhart** [comment]
A good example would be to register as a service to Consul and provide an endpoint that lists all registered services.

**Comment by tayzlor** [comment]
+1 for this - if you feel like contributing a spring boot docker container (simple rest API example) that would be awesome!

**Comment by rhart** [comment]
Sure, would defo be up for that.  New repo required?  apollo-spring-boot?

**Comment by tayzlor** [comment]
Yep - unless there is a pre-existing REST spring boot example already on https://registry.hub.docker.com which we could just pinch and use to deploy

**Comment by rhart** [comment]
Any pre-existing one's are unlikely to be using Consul for service discovery.  Leave it with me and I'll get a new repo set up.
