### ISSUE TITLE
Combine packer JSON files

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#116]
We repeat ourselves in the packer JSON files a lot, we should be able to trim down the number of files we have (while still keeping it sensible). 

e.g. it should be easy to merge digitalocean / aws and google together.
The vagrant / virtualbox one is the only one thats a bit different than those but might still be easy to merge into the same one and limit the scripts to that builder using the "only" concept in packer

**Comment by enxebre** [comment]
Closing this as we've decided to keep separate files at the moment see https://github.com/mitchellh/packer/issues/2048 and https://github.com/mitchellh/packer/issues/1861
