### ISSUE TITLE
Improve haproxy consul template to handle additional cases

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#122]
In another project we used tags to only surface things on the load balancer that were tagged "external" so internal services just talked to each other over the weave network. Additionally we also used the consul K/V store to store URL for some services (again another project) and then put the acl on it - e.g. the template looked something like -

```
{{range services}}
  {{$service := .Name}}
  {{range .Tags}}
    {{$tag := .}}
    {{if eq $tag "qa" "uat" }}
      {{with service ($service | printf "external.%s") }}
      acl acl_{{$tag}}_{{$service}} hdr(host) -i {{$service}}.{{$tag}}.DOMAIN
    use_backend {{$tag}}_{{$service}} if acl_{{$tag}}_{{$service}}
      {{end}}
   {{end}}
{{end}}
{{end}}
```

this meant we only surfaced any services that were tagged QA or UAT AND external to the load balancer (so nginx in QA environment would be available at nginx.qa.DOMAIN).

For handling filtering by URL on the ACL we did -

```
acl is_{{$tag}}_{{$service}} path_beg -i {{key ($service | printf "%s/base-url")}}
```
which basically looked up SERVICE_NAME/base-url from the consul K/V store.

One idea that popped into my head is that we could utilise - {{env "ENV_VARIABLE"}} within the consul-template itself, which we could pass through either tags / service name or some other metadata. This would have the benefit of being able to be passed straight through from docker via docker run -e ENV_VARIABLE=value so would be easy to hook into externally without changing the actual config file itself.

We probably want to think about how we craft this template so we only surface things we want to here.

**Comment by wallies** [comment]
closing as we now use traefik
