### ISSUE TITLE
  Move consul out to a docker container

### ISSUE THREAD

**Issue by wallies** [Capgemini/Apollo#129]
https://github.com/progrium/docker-consul

**Comment by keithchambers** [comment]
FFIW we had no-so-great luck with Consul in Docker and moved it out.

**Comment by tayzlor** [comment]
Thanks for the feedback Keith! Any particular issues you were facing with the Docker setup?

**Comment by keithchambers** [comment]
ARP caching, restarting Docker takes it down, and just way too much code around making it all work. In the end it was far simpler and more reliable to run Consul outside a container.

**Comment by wallies** [comment]
Keith our main motivation for moving this out to a container is like other components, so we have very minimal on our base image. Eventually we aim to have nothing on the base image, so we can use public shared images like on the nat server.

**Comment by enxebre** [comment]
There are new images for consul agent and master provided by gliderlabs https://registry.hub.docker.com/repos/gliderlabs/

**Comment by wallies** [comment]
this is now supported in coreos devel branch
