### ISSUE TITLE
Discuss and Implement docker container logging

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#130]
Needs a wider discussion around approach.

http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/

**Comment by tayzlor** [comment]
I think we should also consider using fluentd instead of logstash, since that's what kubernetes are using by default - http://blog.raintown.org/2014/11/logging-kubernetes-pods-using-fluentd.html

There's also going to be a fluentd log driver for docker as part of 1.8 - http://blog.treasuredata.com/blog/2015/08/03/5-use-cases-docker-fluentd/

**Comment by wallies** [comment]
i like the fluentd log driver, use case and standardising on something with the community. Dont particular like how fluentd do plugins and its dependency on ruby
