### ISSUE TITLE
Why is Atlas a requirement ??

### ISSUE THREAD

**Issue by andreijs** [Capgemini/Apollo#140]
Hey,

Is atlas a requirement to run this project?

Regards

**Comment by tayzlor** [comment]
Depends, If you are using the vagrant provider you wont need Atlas at all.

At the moment if you are using digitalocean or AWS you will. Although for AWS we have made our AMI public (as well as the Atlas artifact) so you should be able to use that https://atlas.hashicorp.com/capgemini/artifacts/apollo-mesos-ubuntu-14.04-amd64.

Unfortunately digitalocean does not support public images so you won't be able to re-use our artifact there but will need to bake your own at present.

Atlas is used at present for artifacts and provisioning from them and also for consul integration (a la https://www.consul.io/docs/guides/atlas.html). This means when you provision you should get a monitoring dashboard with the health of your consul instances at https://atlas.hashicorp.com/environments.

I'm open to discussion about atlas support and whether we maintain it, drop it or change it. I think in an ideal world we would have the ability to deploy using atlas artifacts but by default that would be turned off and just use AMI / droplet IDs in the terraform configuration. Unfortunately terraform does not do conditional logic yet, See this issue -
https://github.com/hashicorp/terraform/issues/1604

If it did we could do something like - 

```if ${var.atlas_enabled} {
  resource "atlas_artifact" "machine" {
    name = "${var.atlas_artifact.name}"
    type = "aws.ami"
  }
}

then in a resource 

resource "aws_instance" "machine" {
  if ${var.atlas_enabled} {
     ami = "${atlas_artifact.machine.id}"
  } else {
     ami = "${var.ami_string}"
  }
}
```

Reversing the atlas support would be fairly trivial. in fact it was only recently added for digitalocean in this commit https://github.com/Capgemini/Apollo/commit/163c735d09928df34446257fe7f177a3d182f21a

We'll have an investigation and see if we can make the requirement around atlas a bit more flexible

**Comment by wallies** [comment]
We should make Atlas one of the frameworks or things we make pluggable like marathon, vault etc.

**Comment by enxebre** [comment]
Lets figure out the best way to this pluggable. I find atlas a good default approach as for aws it allows to the user skip the step of building the image. Not sure is gce or do is planning to allow publi images at some point.

**Comment by tayzlor** [comment]
Wondering if we might be able to use terraform modules to optionally load the atlas configuration or fallback to default if atlas is not enabled. For example -

in ```terraform/aws``` create a ```default``` and ```atlas``` folder. move the atlas configuration to a terraform file inside the atlas folder. in the main terraform files do something like - 

```
variable "config_type" {
 default = "atlas"
 description = "Type of configuration to use. can be either default/atlas"
}

module "artifact" {
    source = "./${var.config_type}"
}
```

the default and atlas modules would provide the same output that could be used in the ```ami``` field of the resource type. This would mean we could use atlas optionally by setting config_type via an environment variable. Need to have a play around and see if this works though

**Comment by enxebre** [comment]
I raised a ticker here https://github.com/hashicorp/terraform/issues/1846

**Comment by tayzlor** [comment]
Atlas is no longer a requirement for the project - we've removed the Atlas support. Closing this.
