### ISSUE TITLE
Change terraform environment variables to use TF_VAR... rather than pass -var on the command line

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#141]
Since this got merged https://github.com/hashicorp/terraform/pull/1621

Should now support setting TF_VAR_name. this means we can avoid having to pass continuous -var= all the time in util.sh. Probably a good idea to wait for terraform 0.5 before implementing

**Comment by tayzlor** [comment]
terraform 0.5 now out so including this for 0.2

**Comment by enxebre** [comment]
See #152
