### ISSUE TITLE
Allow toggling of debug output via a single switch (env var)

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#148]
We should be able to toggle ansible / terraform verbosity logs via a single debug switch in.

so turning on verbose would do ```TERRAFORM_LOG=1``` and run ansible with ```-vvv```

**Comment by asnaedae** [comment]
Would the preference be to set via environment variable (which would follow convention with cloud provisioning patterns) or an option to apollo-launch.sh?

**Comment by tayzlor** [comment]
I think my personal preference would be to set a single environment variable (APOLLO_LOG??), which would in turn set -vvv  on ansible and TERRAFORM_LOG=1

**Comment by asnaedae** [comment]
It's what I was thinking would match with  existing usage of of the APOLLO_ namespace, will put together a PR

**Comment by tayzlor** [comment]
Only thing we need to consider is how this plays with https://github.com/Capgemini/Apollo/issues/152
