### ISSUE TITLE
Discuss, agree, implement plan for pluggable approach to provisioning infra services via terraform

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#16]
It would be nice if we had pluggability so that we could mix and match our infrastructure on-demand. 
For example we should be able to pick and choose which mesos frameworks to install http://mesosphere.com/docs/frameworks/ at runtime.

This should be possible by extracting stuff out to terraform modules https://www.terraform.io/docs/configuration/modules.html , and then composing them as we wish.

Later down the line we might have some higher order tool (command line / UI) do the composing of the terraform plan, I dont think thats needed imminently, but a way forward for implementing the underlying pluggability is desired.

**Comment by enxebre** [comment]
I'll evaluate the integration of https://github.com/mesosphere/dcos-cli out of dcos ("Note that the DCOS CLI has tight integration with DCOS and certain functionality may not work as expected or at all when using it directly with Mesos and Marathon.")

That could solve part of the description above related to the frameworks and https://github.com/Capgemini/Apollo/issues/291 while we'd be in line with the community standards.

**Comment by wallies** [comment]
closing as we have dcos_cli for frameworks and apps and modules for terraform
