### ISSUE TITLE
Experiment setting mesos up in a coreOS cluster

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#17]
Could possibly borrow some stuff from here - 
https://gist.github.com/andyshinn/92f9175a8cc79185314e

Not sure of the implications or extra hoops required to run mesos on coreOS. Seems some people have done some experimentations - 

http://mesosphere.com/docs/tutorials/mesosphere-on-a-single-coreos-instance/
https://groups.google.com/forum/#!searchin/coreos-user/mesos/coreos-user/hsjuvrL8eM0/wgHVVEARxnYJ
https://github.com/veverjak/coreos-mesos-marathon

**Comment by wallies** [comment]
devel branch now has support for coreos
