### ISSUE TITLE
Make plugin system more dynamic

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#171]
See #105 and https://github.com/Capgemini/Apollo/pull/138/files 
Once this get in, and we have more than one case we need to find the best way for making the plugin system more dynamic so no need to modify any code for hooking up a new plugin.
One idea would be make every plugin responsible of its own playbook. The poblem of this is that it'd couple the plugin with the Apollo core too much as the plugin should be aware of how core makes inventory groups.

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/Apollo/pull/357
