### ISSUE TITLE
Improve mesos spec tests

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#182]
We only test the service is running and the package is installed.

I'm fairly certain we could test for some of the files. Just need to be careful around the content of them as that is configurable, but we could test for the existence of them.

**Comment by wallies** [comment]
could also test that there is a leader and there is correct number of masters of slaves

**Comment by tayzlor** [comment]
This was partly fixed in https://github.com/Capgemini/Apollo/pull/191 (for the mesos master).

Just need the slave tests now

**Comment by tayzlor** [comment]
Closing via #194
