### ISSUE TITLE
No such key file & misc errors

### ISSUE THREAD

**Issue by haf** [Capgemini/Apollo#200]
```
sh bootstrap/apollo-launch.sh
Starting cluster using provider: digitalocean
... calling verify-prereqs
... calling apollo-launch
~/dev/_scratch/apollo/terraform/digitalocean ~/dev/_scratch/apollo
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* 1 error(s) occurred:

* file: open : no such file or directory in:

${file(var.key_file)}
```

And in `bootstrap/digitalocean/config-default.sh`:

`TF_VAR_key_file=${TF_VAR_key_file:-/Users/henrik.feldt/.ssh/digitalocean.pub}`

...which exists.

**Comment by tayzlor** [comment]
@haf Can you confirm which version of terraform you are using? You need to be on >= 0.5.0

**Comment by haf** [comment]
I just downloaded everything latest

**Comment by enxebre** [comment]
The way the script it is right now you would need to export the variable for overriding before running sh bootstrap/apollo-launch.sh

```
export TF_VAR_key_file=/Users/henrik.feldt/.ssh/digitalocean.pub
```
 Just created https://github.com/Capgemini/Apollo/pull/201

**Comment by haf** [comment]
Still doesn't work:

```
$ ssh-keygen -t ssh-rsa -C henrik@haf.se
... snip
$ sh ...

* Error creating SSH Key: Error creating SSH key: API Error: unprocessable_entity: Key invalid type, we support 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'
Error applying plan:

2 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error creating SSH Key: Error creating SSH key: API Error: unprocessable_entity: Key invalid type, we support 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'
* 1 error(s) occurred:

```

**Comment by haf** [comment]
A little bit rough around the edges; the ams2 region didn't apply and the key must not already exist in DigitalOcean's API; and there's not full docs on the DIGITALOCEAN_{IMAGE,REGION} etc keys needed for Atlas.

**Comment by haf** [comment]
Then when it's done, it says:

```
ERROR: Inventory script (bootstrap/../bootstrap/digitalocean/../../inventory/digitalocean/digital_ocean.py) had an execution error:
```

Without outputting an error message.

**Comment by haf** [comment]
So now that it's up, what's next? SSHing to a single instance shows that docker and zookeeper are both not running... Does that have something to do with the error message above?

**Comment by tayzlor** [comment]
Maybe try again after #201 just got merged. Try a destroy and a full build. 
To get DO image IDs you can use something like tugboat - https://github.com/pearkes/tugboat

Looks like they won't be running because of the above error - which will likely have meant that your ansible provisioning has failed. Just checking you installed the correct version of ansible via requirements.txt ?

...and thanks v much for the bug reports!

**Comment by haf** [comment]
Ok, I'm going to try the vagrant option, to avoid incurring charges.

No, I didn't do anything but what the guide said, but I did run pip with requirements.txt, so if it installed something other than what it should, I won't know about it. I do have virtualenv set up, so perhaps that should be an option in the description?

It would be a good thing to document the very basic deployment pattern a platform like this supports, because I couldn't find anything about that in the docs.

**Comment by haf** [comment]
Vagrant doesn't work at all:

```
==> master1: Waiting for machine to boot. This may take a few minutes...
    master1: SSH address: 127.0.0.1:2222
    master1: SSH username: vagrant
    master1: SSH auth method: private key
    master1: Warning: Connection timeout. Retrying...
    master1:
    master1: Vagrant insecure key detected. Vagrant will automatically replace
    master1: this with a newly generated keypair for better security.
    master1:
    master1: Inserting generated public key within guest...
    master1: Removing insecure key from the guest if its present...
    master1: Key inserted! Disconnecting and reconnecting using new SSH key...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:
vagrant@127.0.0.1's password:
vagrant@127.0.0.1's password:
```

**Comment by wallies** [comment]
@haf can you provide you vagrant ssh config 'vagrant ssh-config' please

**Comment by haf** [comment]
```
Host master1
  HostName 127.0.0.1
  User vagrant
  Port 2200
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/henrik.feldt/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.
```

**Comment by wallies** [comment]
@haf #202 i suspect should solve your issues. As it checks the vagrant version

**Comment by haf** [comment]
This is a bug in how boxes are packaged; previous versions of vagrant, which might be used behind the scenes of atlas replaced the .ssh key of the box before it could be packaged. veewee doesn't experience this issue, which is how most vagrant-box pipelines are built, still.

Running as sudo therefore doesn't help, as this is a query from the SSH daemon/client. Otherwise you'd be saying my current computer user is named 'vagrant' which you've seen in the paths, it's not.

As with all other version-questions, I'm using the latest vagrant.

**Comment by tayzlor** [comment]
Added https://github.com/Capgemini/Apollo/commit/8deffd6ac6128814bc0e0accc9c31801e202b5e6 around docs fix for looking up DO images manually. Investigating the vagrant related issues today...

**Comment by tayzlor** [comment]
@haf we can't replicate your issue here. We did however change our box names and rebuild them to https://atlas.hashicorp.com/capgemini/boxes/apollo after https://github.com/Capgemini/Apollo/pull/185 got in, as well as add a couple of tweaks to the ansible.cfg file.

Can you try pulling latest master and building from scratch from the new box. If it fails can you run with ```VAGRANT_LOG=1``` on (which should give you a very verbose output) and paste the debug logs here.

**Comment by tayzlor** [comment]
Closing, this should be working correctly against latest master. Please re-open if you still have issues.
