### ISSUE TITLE
Can we implement the setup on baremetal or on VmWare or on LocalServer

### ISSUE THREAD

**Issue by vijaykumar0690** [Capgemini/Apollo#212]
Hi Team,

I see you are supporting only AWS,DigitalOcean. can we use the setup on baremetal or on ESXI Servers or on VMWare.

Regards,
Vijay

**Comment by wallies** [comment]
As part of #213 and #214 we will be doing this.

**Comment by tayzlor** [comment]
Thanks for the question, Closing this in favour of the above 2 issues. Please follow them to keep updated, or help if you can!
