### ISSUE TITLE
Unbound variable in common.sh

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#238]
bootstrap/../bootstrap/common.sh: line 68: mesos_zk_url: unbound variable.

See https://app.wercker.com/#deploystep/5561a95b98eb5da12603637a

**Comment by enxebre** [comment]
Cant reproduce this out of the wercker world. This seems to fix it though. https://github.com/Capgemini/Apollo/pull/240

**Comment by tayzlor** [comment]
Closing via #240
