### ISSUE TITLE
Cloud provisioning / wercker deploy random errors on Ansible gather facts

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#239]
This looks like because the SSH port is not yet available. I think we need to add a 'wait_for' to wait on the SSH port. 

See this issue - 

https://github.com/geerlingguy/ansible-for-devops/issues/3

And this commit for the fix -

https://github.com/geerlingguy/ansible-for-devops/commit/24651edf37f7c682a4d292578aceabcc8427c36b

**Comment by enxebre** [comment]
WIP here https://github.com/Capgemini/Apollo/pull/242
