### ISSUE TITLE
Upgrade ubuntu to kernel 3.18 to use overlayfs

### ISSUE THREAD

**Issue by wallies** [Capgemini/Apollo#25]
http://ubuntuhandbook.org/index.php/2014/12/install-linux-kernel-3-18-ubuntu/

**Comment by wallies** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/pull/180/files

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/Apollo/commit/ed4a75ef62950762d2a9db2f9707e090ac459fbe
