### ISSUE TITLE
Add support for running Apollo behind a proxy

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#250]
At the moment if you run up the vagrant machine behind a proxy you will run into issues downloading Docker containers and downloading the python docker lib.

We should be able to circumvent these issues by adding proxy support to ansible and the relevant roles.
Needs a bit of further investigation to figure out the best approach. 

One simple method that springs to mind would be to follow something like - 

https://docs.ansible.com/playbooks_environment.html and leave the ```proxy_env``` commented out in the playbook vars.

if ```proxy_env``` is set (uncommented) - set it on the tasks we need to (e.g. python docker lib download). We can also add it to ```/etc/default/docker``` as an option too (to handle the container downloads)

**Comment by andrewharmellaw** [comment]
+1
