### ISSUE TITLE
Split mesos_local_address to 2 variables - mesos_ip and mesos_hostname

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#268]
We use it in 2 places to set -

```
/etc/mesos-master/ip
/etc/mesos-master/hostname
```
and for slaves too. Would be better if this was split to 2 variables for flexibility (if you want to set the hostname to a DNS name and the IP to an IP address for example).

We'd also need to update the Vagrantfile where it is injecting these values.

**Comment by ravbaba** [comment]
It looks like it has been done. The variable "mesos_hostname" doesn't exist in the project. I think we can close the issue.

**Comment by tayzlor** [comment]
Closing
