### ISSUE TITLE
Improve marathon spec tests

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#272]
After https://github.com/Capgemini/Apollo/commit/4f44df0b042346540910758273934c2b4c02a2ba got in, we could improve the spec tests around marathon to include - 

- [ ] Test existence of file ```marathon-wait-for-listen.sh``` (with correct mode etc...)
- [ ] Run the above file and test we get a 'pong'
- [ ] Test ```/etc/init/marathon.override``` does NOT exist
- [ ] Test marathon consul service definition file exists
- [ ] Test ```/etc/init/marathon.conf``` exists with correct content/permissions

**Comment by enxebre** [comment]
this is covered by https://github.com/Capgemini/Apollo/pull/338/files

**Comment by enxebre** [comment]
also https://github.com/Capgemini/Apollo/pull/344/files
