### ISSUE TITLE
ELB not balancing correctly to slave node haproxy containers

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#275]
![screen shot 2015-06-02 at 09 22 48](https://cloud.githubusercontent.com/assets/1681896/7931489/00260978-0909-11e5-8db5-f03de186a8d2.png)

This is because it tries to do a health check to the slave IP address on port 80 which returns a 503 (because there is no backend set up in haproxy to return from that)

**Comment by tayzlor** [comment]
We need to clarify how we're using the ELB here. We might want to do something like this https://github.com/jvehent/haproxy-aws

**Comment by tayzlor** [comment]
This Pull request adds support for the Proxy protocol in the ELB https://github.com/hashicorp/terraform/pull/1749/

**Comment by enxebre** [comment]
closing this as per https://github.com/Capgemini/Apollo/commit/785e790d1c623f73d33029dd21b74779873b2056
