### ISSUE TITLE
Create a wercker deploy step for packer push

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#286]
We should be able to manually push a button in wercker that initiates a packer push to atlas for the specified packer templates. 

This means we can optionally build new versions of boxes.

We need to be careful here around the use of the 'version' flag, to make sure we allow it to be incremented correctly on a packer push.

I dont think packer push supports attaching vars, so we might need to rethink the versioning strategy.

**Comment by wallies** [comment]
packer is no longer supported going forward, so closing this out
