### ISSUE TITLE
Drupal example container dies after a while

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#289]
I get into a state where the container dies and stops running, then mesos just spins around trying to constantly recreate the container. It comes back for a while then dies again.

We have a marathon healthcheck configured as - 

```
 "healthChecks": [{
        "path": "/",
        "portIndex": 0,
        "protocol": "HTTP",
        "gracePeriodSeconds": 30,
        "intervalSeconds": 10,
        "timeoutSeconds": 20,
        "maxConsecutiveFailures": 3
      }
```

which may be causing some of the spinning issues. When the container comes back and you access it through the marathon IP you see - 

```
Fatal error: Class 'SelectQueryExtender' not found in /var/www/html/includes/pager.inc on line 15
```

I also noticed some of the permissions on the files inside the container looked a bit weird, e.g. were not assigned to www-data

**Comment by tayzlor** [comment]
Trying with Drupal8 - get this on installation - 

```
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /core/install.php?langcode=en&profile=standard&id=1&op=do_nojs&op=do
StatusText: error
ResponseText: 
ReadyState: 0
```

**Comment by tayzlor** [comment]
Bumping the mysql container to 1024MB seems to solve some of the hanging..

Now we just get this error on install - 

![screen shot 2015-06-04 at 10 04 18](https://cloud.githubusercontent.com/assets/1681896/7980651/1c378346-0aa1-11e5-8463-274886644309.png)

**Comment by tayzlor** [comment]
tracking fixes in branch - drupal-examples

**Comment by wallies** [comment]
ive got a fix for DNS, using DNSimple

**Comment by tayzlor** [comment]
Testing this on AWS, with a ```c3.large``` machine and the updated JSON files, everything installs fine. Will open a PR for the updated JSON and some docs around the instance requirements.
