### ISSUE TITLE
Fix specs for digitalocean

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#325]
When dpeloying from wercker on Digitalocean:
 1) Docker container "weave" should be running
On host `mesos_masters'
Failure/Error: it { should be_running }
MultiJson::ParseError:
784: unexpected token at 'Error: No such image or container: weave
[]
'
/bin/sh -c docker\ inspect\ weave
Error: No such image or container: weave
[]

https://app.wercker.com/#deploystep/55881a3e9e5d0cdb461345b5

**Comment by enxebre** [comment]
This need to be tested against after builing the DO image using the latest version of the packer template.

**Comment by enxebre** [comment]
Weave service is not running and logs showing: 
network 10.128.0.0/10 would overlap with route 10.131.0.0/16
Default -iprange 10.128.0.0/10 overlaps with existing route.
Please pick another range and set it on all hosts.

**Comment by enxebre** [comment]
Think this is because default value for iprange overlaps with default Digitalocean internal subnet. So setting something more restrictive should work like:
${WEAVE} launch -iprange "{{ weave_docker_subnet }}" ${PEERS} 
having that:
 weave_docker_subnet:  10.2.{{ loop.index }}.0/24

See https://github.com/Capgemini/Apollo/pull/327/files

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/Apollo/commit/5ade856b1523138817ebdf196495e06811ac611b

**Comment by wallies** [comment]
closing in favour of #583
