### ISSUE TITLE
Investigate implementing weave fast data path

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#337]
http://blog.weave.works/2015/06/12/weave-fast-datapath/

**Comment by zytek** [comment]
+1, userspace networking rules out apollo for production deployments.

**Comment by enxebre** [comment]
this has just been released https://github.com/weaveworks/weave/releases/tag/v1.2.0

**Comment by tayzlor** [comment]
Closing this as we moved to weave FDP in this commit https://github.com/Capgemini/Apollo/commit/b03d566e5937e114dcbeaff49326e94203b88f14
