### ISSUE TITLE
bootstrap/apollo-launch.sh: 5: set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by ravbaba** [Capgemini/Apollo#349]
I got the above error running apollo-launch.sh script on ubuntu 15.04.

Test has been done with a vagrant provider.

Vagrant version 1.7.2
Python 2.7.9
The latest version of Virtualbox

**Comment by wallies** [comment]
According to bash's changelog pipefail was added in bash-3.0-alpha. Are you sure your /bin/sh is bash?
I have created https://github.com/Capgemini/Apollo/pull/350 to fix this anyway

**Comment by enxebre** [comment]
Guessing this is because In Ubuntu sh points to dash. Do you have same issue running "/bin/bash bootstrap/apollo-launch.sh" ?

**Comment by ravbaba** [comment]
yes, running "/bin/bash bootstrap/apollo-launch.sh" solves the problem

**Comment by ravbaba** [comment]
Just temporary fix for ubuntu users. As enxebre mentioned /bin/sh points to dash, to check it you can run: 

ls -al /bin/sh

and it should show you

/bin/sh -> dash

if you want change it to point it to bash instead remove symbolic link and create new one:

sudo rm /bin/sh
sudo ln -s /bin/bash /bin/sh
