### ISSUE TITLE
install_consul.sh failed in packer

### ISSUE THREAD

**Issue by shirkevich** [Capgemini/Apollo#411]
When trying to build ami image in packer I got:
```
amazon-ebs: + sudo cp /tmp/consul.conf /etc/init/consul.conf
amazon-ebs: cp: cannot stat ‘/tmp/consul.conf’: No such file or directory
```

This is because 0.5.2_linux_*.zip contains only `consul` binary and no config files.

**Comment by enxebre** [comment]
Thanks for reporting this, we''ll have a look. However in the mean time feel free to use the default artifacts provided by Apollo as they link to aws public image.

**Comment by tayzlor** [comment]
https://atlas.hashicorp.com/capgemini/artifacts/apollo-ubuntu-14.04-amd64/types/aws.ami

**Comment by shirkevich** [comment]
@enxebre, thanks, but I need hvm image for eu-central-1 region, so I need to rebuild ami from scratch.

**Comment by shirkevich** [comment]
By the way, maybe it's good time to move consul to docker container? https://github.com/Capgemini/Apollo/issues/129

I would like to work on this task, cause we're using internally dockerised clustered consul with no problems. https://registry.hub.docker.com/u/progrium/consul/

**Comment by tayzlor** [comment]
@shirkevich nice, would love to see a PR on that. We're aiming to gradually move the entire stack to Docker

**Comment by enxebre** [comment]
Hey @shirkevich issue shouldn't happen if you pull latest changes in master.
Consul ticket would be brilliant.
Thanks!

**Comment by shirkevich** [comment]
@enxebre right you are! Problem is gone in current master. You can close this issue, but i don't understand how kernel upgrade is related to consul config files...?!

**Comment by enxebre** [comment]
Hey @shirkevich the kernel upgrade requires a system reboot which remove the files in /tmp which is where we are telling packer to store the consul config so when the consul script tries to use it, it is not there any more. There are more issues related to kernel upgrade so we are reverting the change temporally while we fix them :)
Thanks!

**Comment by wallies** [comment]
@shirkevich our next release 0.2 will be changing the ami we build to hvm. This will be released within the next couple of days
