### ISSUE TITLE
Deploy on aws fails on bastion

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#432]
aws_instance.bastion (remote-exec): Post http:///var/run/docker.sock/v1.19/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon w
ithout TLS?
aws_instance.bastion: Error: 1 error(s) occurred:

**Comment by tayzlor** [comment]
Fixed in https://github.com/Capgemini/Apollo/commit/4117f06a47a70f0ff45c543b592dc2b32ec8e54b
