### ISSUE TITLE
Bump up Ansible requirement to 2.0 once it is out

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#443]
Bump up Ansible requirement to 2.0 once it is out
Due to https://github.com/ansible/ansible-modules-core/pull/1767 we can't set memory limit in the docker containers via ansible docker-module at the moment.

Related to:
https://github.com/Capgemini/Apollo/issues/386
https://github.com/Capgemini/Apollo/pull/413

**Comment by tayzlor** [comment]
Related https://github.com/ansible/ansible-modules-core/issues/1707 looks like there might be a potential workaround for 1.9.x ??

**Comment by tayzlor** [comment]
moving out of 0.4
