### ISSUE TITLE
Move to the new docker official repos that install docker-engine instead if lxc-docker

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#445]
Move to  new docker official repos https://blog.docker.com/2015/07/new-apt-and-yum-rep
We want to do that once the new version after 1.7.1 get relased as it will include https://github.com/docker/docker/issues/14738
which fixes https://github.com/Capgemini/Apollo/issues/428

**Comment by enxebre** [comment]
See https://github.com/docker/distribution/wiki

**Comment by enxebre** [comment]
with 1.7.0 we suffer of problem fix in 1.7.1 "Fix local dns lookups added to resolv.conf"
with 1.7.1 we suffer of https://github.com/docker/docker/issues/14738
Need to upgrade to 1.8.0 which hopefully wil fix both.

**Comment by wallies** [comment]
Do we know wheb 1.8.0 is released? There is that patched binary with the 1.7.1 release in the issue. We could use that in the meantime to stabalise.

**Comment by enxebre** [comment]
As per the link in comment above it will be release tomorrow https://github.com/docker/distribution/wiki
Otherwise could use the patch or put in place a different solution

**Comment by wallies** [comment]
Nah i would do a PR with the new repos ready for tomorrow

**Comment by tayzlor** [comment]
Resolved in https://github.com/Capgemini/Apollo/pull/449
