### ISSUE TITLE
apollo-launch.sh failing with Vagrant

### ISSUE THREAD

**Issue by earldouglas** [Capgemini/Apollo#478]
When bootstrapping a fresh Apollo instance using the Vagrant provider, it has trouble during the *download weave scope* and *run zookeeper container* tasks:

```
TASK: [weave | download weave scope] ****************************************** 
changed: [slave1]
failed: [master3] => {"dest": "/usr/local/bin/scope", "failed": true, "response": "Request failed: <urlopen error [Errno -2] Name or service not known>", "state": "absent", "status_code": -1, "url": "https://github.com/weaveworks/scope/releases/download/latest_release/scope"}
msg: Request failed
changed: [master1]
failed: [master2] => {"dest": "/usr/local/bin/scope", "failed": true, "response": "Request failed: <urlopen error [Errno -2] Name or service not known>", "state": "absent", "status_code": -1, "url": "https://github.com/weaveworks/scope/releases/download/latest_release/scope"}
msg: Request failed
```

```
TASK: [zookeeper | run zookeeper container] *********************************** 
failed: [master1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')),)
```

At this point the cluster seems to be in an unhappy state -- several of the services are failing their health checks, or missing entirely.

```
FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/james/site.retry

master1                    : ok=46   changed=38   unreachable=0    failed=1   
master2                    : ok=20   changed=15   unreachable=0    failed=1   
master3                    : ok=20   changed=15   unreachable=0    failed=1   
slave1                     : ok=39   changed=31   unreachable=0    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Re-running *apollo-launch.sh* doesn't seem to recover.

**Comment by earldouglas** [comment]
This was working just a few hours ago, and now is consistently failing.  I thing something might be wrong with my local environment, but I haven't been able to identify it.

**Comment by wallies** [comment]
Can you let us know the different versions of the different products you are using e.g. Vagrant, Ansible, Terraform etc.

**Comment by earldouglas** [comment]
* Vagrant 1.7.4
* ansible 1.9.2
* VirtualBox 5.0.2
* Python 2.7.6
* pip 1.5.4
* terraform doesn't appear to be installed

**Comment by wallies** [comment]
@earldouglas we think we have found the issue. Can you run export ANSIBLE_LOG="-vvvv" and then rerun apollo-launch. This will give us a lot more debug information on whats failing. Cheers

**Comment by earldouglas** [comment]
Hooray, it's working again (after a pull)!  \o/

Do you still want my stdout log, even though it's now working?

**Comment by wallies** [comment]
If its all working now, should be fine without the log. I will the issue open for another day just in case. We will be rebuilding the packer image within the next day or so, which should be a lot more stable.
