### ISSUE TITLE
How to reduce number of mesos-master

### ISSUE THREAD

**Issue by ismail0352** [Capgemini/Apollo#509]
I want to know is there any way of reducing number of masters in apollo for cluster mode?
I tried commenting the IP's in the vagrant.yml file but when i run launch script it starts asking for master3
Then i commented in .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory but still the same output

**Comment by enxebre** [comment]
Hi @ismail0352 the way to do it for vagrant is to modify the config in vagrant.yml which is used by the Vagrantfile. For the others cloud providers you can just do it via environment variable e.g export TF_masters=2
However the smallest cluster recommended for high availability is three master

**Comment by ismail0352** [comment]
Its true that we must have atleast 3 masters, but as of now i dont have that much of hardware thus i only wanted to have 1 master and 1 slave. 
I tried commenting the extra IP's given in vagrant.yml file, but when i run the launch script after creating the first VM vagrant gives an error    "The machine with the name 'master3' was not found configured for
this Vagrant environment."

**Comment by enxebre** [comment]
I wonder if you modified the vagranat.yml after a previous attemp of running vagrant so it is expecting the 3 masters to be there. Could you try by running "vagrant destroy" first so making sure Vagrant has no info stored and then deploy the cluster? thanks!

**Comment by ismail0352** [comment]
I used vagrant destroy first, before running the launch script.
Below is my vagrant.yml file

masters:
  # Memory and Cpus setting
  ##########################
  mem: 512
  cpus: 1
  # Actual instances
  ##################
  ips:
      - 172.31.1.11
     # - 172.31.1.12
     # - 172.31.1.13
# By default only one slave is set, to increase that number just add new ips.
slaves:
# Memory and Cpus setting
  ##########################
  mem: 512
  cpus: 1
  # Slave IPs - must be in the same private address range as the master instances
  # See http://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces
  ips:
      - 172.31.1.14
# Mesos master quorum: quorum > (number of masters)/2
# For standalone mode is always 1
mesos_master_quorum: 1
# Expected number of server nodes
# For standalone mode is always 1
consul_bootstrap_expect: 1

This might help
Thanks

**Comment by enxebre** [comment]
I can't reproduce it. Could you just sent the output of "vagrant status"? sounds to me like vagrant using some garbage data from previews build. Thanks!

**Comment by ismail0352** [comment]
Output of launch script
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling apollo-launch
Bringing machine 'master1' up with 'virtualbox' provider...
Bringing machine 'slave1' up with 'virtualbox' provider...
==> master1: Checking if box 'capgemini/apollo' is up to date...
==> master1: VirtualBox VM is already running.
==> slave1: Importing base box 'capgemini/apollo'...
==> slave1: Matching MAC address for NAT networking...
==> slave1: Checking if box 'capgemini/apollo' is up to date...
==> slave1: Setting the name of the VM: vagrant-mesos-slave1
==> slave1: Fixed port collision for 22 => 2222. Now on port 2202.
==> slave1: Clearing any previously set network interfaces...
==> slave1: Preparing network interfaces based on configuration...
    slave1: Adapter 1: nat
    slave1: Adapter 2: hostonly
==> slave1: Forwarding ports...
    slave1: 22 => 2202 (adapter 1)
==> slave1: Running 'pre-boot' VM customizations...
==> slave1: Booting VM...
==> slave1: Waiting for machine to boot. This may take a few minutes...
    slave1: SSH address: 127.0.0.1:2202
    slave1: SSH username: vagrant
    slave1: SSH auth method: private key
    slave1: Warning: Connection timeout. Retrying...
    slave1: Warning: Remote connection disconnect. Retrying...
==> slave1: Machine booted and ready!
==> slave1: Checking for guest additions in VM...
    slave1: The guest additions on this VM do not match the installed version of
    slave1: VirtualBox! In most cases this is fine, but in rare cases it can
    slave1: prevent things such as shared folders from working properly. If you see
    slave1: shared folder errors, please make sure the guest additions within the
    slave1: virtual machine match the version of VirtualBox you have installed on
    slave1: your host and reload your VM.
    slave1:
    slave1: Guest Additions Version: 5.0.2
    slave1: VirtualBox Version: 4.3
==> slave1: Setting hostname...
==> slave1: Configuring and enabling network interfaces...
==> slave1: Mounting shared folders...
    slave1: /vagrant => /root/Apollo-Capgemini/apollo
==> slave1: Updating /etc/hosts file on active guest machines...
The machine with the name 'master2' was not found configured for
this Vagrant environment.

**Comment by ismail0352** [comment]
output of vagrant stutus:
Current machine states:

master1                   running (virtualbox)
slave1                    running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

**Comment by enxebre** [comment]
base on that output seems like the hostmanager puging is trying to use some garbage data for upgrading the host file, what do you get by running "vagrant hostmanager"
Also just FYI you can also run the standalone mode which run in one single vm.
https://github.com/Capgemini/Apollo/blob/master/docs/getting-started-guides/vagrant.md

**Comment by ismail0352** [comment]
Output of vagrant hostmanager:
[master1] Updating /etc/hosts file...
[slave1] Updating /etc/hosts file...
Updating /etc/hosts file on host machine (password may be required)...

**Comment by ismail0352** [comment]
I solved the issue. The issue was with the vagrant commands
Although on the github page it is written that we can handle the VM using vagrant commands such as halt and all. I would personally say that for destroying the VM's please only use the apollo-down.sh script.

Now i am able to get ahead in installations

Why is it keeping records in the /etc/hosts file?
I had to remove all the records present before using the down script. 

Once the down script got executed i was able to launch the next time.
