### ISSUE TITLE
How to reduce number of mesos-master

### ISSUE THREAD

**Issue by ismail0352** [Capgemini/Apollo#510]
I want to know is there any way of reducing number of masters in apollo for cluster mode?
I tried commenting the IP's in the vagrant.yml file but it starts asking for master3
Then i commented in .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory but still the same output

**Comment by enxebre** [comment]
closing this  as it is duplicated https://github.com/Capgemini/Apollo/issues/509
