### ISSUE TITLE
apollo-launch.sh fails on task     marathon | wait for marathon to listen

### ISSUE THREAD

**Issue by ismail0352** [Capgemini/Apollo#511]
Whenever i try to run apollo i get stuck on the marathon part. Below is the actula output:

 NOTIFIED: marathon | wait for marathon to listen >
 --------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

failed: [master3] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.139077", "end": "2015-11-03 09:06:05.372910", "rc": 2, "start": "2015-11-03 09:04:05.233833", "warnings": []}
failed: [master2] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.204387", "end": "2015-11-03 09:06:05.307221", "rc": 2, "start": "2015-11-03 09:04:05.102834", "warnings": []}
failed: [master1] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.488639", "end": "2015-11-03 09:06:05.410037", "rc": 2, "start": "2015-11-03 09:04:04.921398", "warnings": []}

FATAL: all hosts have already failed -- aborting
 __________________________________________________
< NOTIFIED: marathon | wait for marathon to listen >
 --------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

FATAL: no hosts matched or all hosts have already failed -- aborting

FATAL: all hosts have already failed -- aborting
 __________________________________________________
< NOTIFIED: marathon | wait for marathon to listen >
 --------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

FATAL: no hosts matched or all hosts have already failed -- aborting
FATAL: all hosts have already failed -- aborting
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

           to retry, use: --limit @/root/site.retry

master1                    : ok=61   changed=54   unreachable=0    failed=1
master2                    : ok=61   changed=54   unreachable=0    failed=1
master3                    : ok=61   changed=54   unreachable=0    failed=1
slave1                     : ok=37   changed=31   unreachable=0    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by ismail0352** [comment]
Is this error coming because of RAM, becasue i just saw it shows only 130 MB available?

**Comment by ismail0352** [comment]
Output of vagrant hostmanager:
[master1] Updating /etc/hosts file...
[slave1] Updating /etc/hosts file...
Updating /etc/hosts file on host machine (password may be required)...

**Comment by wallies** [comment]
closing as no longer seeing issue in devel branch which will be merged to master soon
