### ISSUE TITLE
Launch Script fails at TASK: [dnsmasq | run dnsmasq container] ***************************************

### ISSUE THREAD

**Issue by ismail0352** [Capgemini/Apollo#531]
This is the error produced while executing launch script.
The output is taken while executing the script in verbose mode.

<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE docker net=host command='-r /etc/dnsmasq.d/resolv.conf~ --conf-dir=/etc/dnsmasq.d' state=started image=andyshinn/dnsmasq name=dnsmasq
<127.0.0.1> REMOTE_MODULE docker net=host command='-r /etc/dnsmasq.d/resolv.conf~ --conf-dir=/etc/dnsmasq.d' state=started image=andyshinn/dnsmasq name=dnsmasq
<127.0.0.1> EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/root/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=gvoyjhekdbmiiywhhmocknngpqislvgo] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-gvoyjhekdbmiiywhhmocknngpqislvgo; LANG=en_US.UTF-8 DOCKER_HOST=unix:///var/run/weave/weave.sock LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
<127.0.0.1> EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2200 -o IdentityFile="/root/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=uzunpwyuqydoyvbsxtpjdpbdvbsmlkfz] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uzunpwyuqydoyvbsxtpjdpbdvbsmlkfz; LANG=en_US.UTF-8 DOCKER_HOST=unix:///var/run/weave/weave.sock LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
failed: [slave1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)
failed: [master1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/site.retry

master1                    : ok=25   changed=18   unreachable=0    failed=1
slave1                     : ok=25   changed=18   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I tried to kill dnsmasq on host machine before executing, also changed /etc/default/docker. But none of them are working.
I also installed, bridge-utils package but no use.

Till yesterday it was working fine, but when i restarted the machine, it started gving me this error.

**Comment by ismail0352** [comment]
Some one from APollo please help me out on this

**Comment by ismail0352** [comment]
The issue is with the andyshinn/dnsmasq image.
Inside the vagrant box, it is getting exited automatically. 
I also saw the syslog and realized it is trying to use IPv6

Output of syslog

Nov 16 07:25:17 master1 kernel: [ 6553.162004] device veth22a505c entered promiscuous mode
Nov 16 07:25:17 master1 kernel: [ 6553.163542] IPv6: ADDRCONF(NETDEV_UP): veth22a505c: link is not ready
Nov 16 07:25:17 master1 kernel: [ 6553.276505] eth0: renamed from vethef6c27d
Nov 16 07:25:17 master1 kernel: [ 6553.277762] IPv6: ADDRCONF(NETDEV_CHANGE): veth22a505c: link becomes ready
Nov 16 07:25:17 master1 kernel: [ 6553.277806] docker0: port 2(veth22a505c) entered forwarding state
Nov 16 07:25:17 master1 kernel: [ 6553.277812] docker0: port 2(veth22a505c) entered forwarding state
Nov 16 07:25:17 master1 kernel: [ 6553.464419] vethef6c27d: renamed from eth0
Nov 16 07:25:17 master1 kernel: [ 6553.478688] docker0: port 2(veth22a505c) entered disabled state
Nov 16 07:25:17 master1 kernel: [ 6553.479889] device veth22a505c left promiscuous mode
Nov 16 07:25:17 master1 kernel: [ 6553.479901] docker0: port 2(veth22a505c) entered disabled state
Nov 16 07:28:45 master1 kernel: [ 6761.142421] device veth019f10c entered promiscuous mode
Nov 16 07:28:45 master1 kernel: [ 6761.143601] IPv6: ADDRCONF(NETDEV_UP): veth019f10c: link is not ready
Nov 16 07:28:45 master1 kernel: [ 6761.298420] eth0: renamed from vethe60b8ac
Nov 16 07:28:45 master1 kernel: [ 6761.298696] IPv6: ADDRCONF(NETDEV_CHANGE): veth019f10c: link becomes ready
Nov 16 07:28:45 master1 kernel: [ 6761.298713] docker0: port 2(veth019f10c) entered forwarding state
Nov 16 07:28:45 master1 kernel: [ 6761.298718] docker0: port 2(veth019f10c) entered forwarding state
Nov 16 07:28:45 master1 kernel: [ 6761.444800] vethe60b8ac: renamed from eth0
Nov 16 07:28:45 master1 kernel: [ 6761.456533] docker0: port 2(veth019f10c) entered disabled state
Nov 16 07:28:45 master1 kernel: [ 6761.458414] device veth019f10c left promiscuous mode
Nov 16 07:28:45 master1 kernel: [ 6761.458458] docker0: port 2(veth019f10c) entered disabled state

Please tell me how to make it use IPv4 or simply run it.

**Comment by perangel** [comment]
I just came across this issue myself today.

My issue was that the socket file being used as the DOCKER_HOST is wrong. It's out of sync with where the socket file actually lives. 

```
// group_vars/all
docker_host: 'unix:///var/run/weave/weave.sock'
```

However the DOCKER_HOST set in the weave environment is one level up
```
vagrant@master1:/var/run/weave$ sudo weave env
export DOCKER_HOST=unix:///var/run/weave.sock ORIG_DOCKER_HOST=
```

This could be due to a version update with weave that is ahead of the latest version of the Vagrant VM being used.

One quick solution for you would be to update `group_vars/all` to reflect the same path as `weave env`. 
Otherwise, you might also rebuild the VM from the packer templates (which I'm in the process of doing right now).

**Comment by ismail0352** [comment]
Thanks a lot. @perangel 
I had the same issue. Went ahead with it. And it worked,
