### ISSUE TITLE
The virtual box image is not available

### ISSUE THREAD

**Issue by liufei11111** [Capgemini/Apollo#544]
Hi, Vagrant image "Capgemini/Apollo" is something magic and could you please share how you generate that? It looks like a mystery and I am curious how it is done.
Thanks.

**Comment by enxebre** [comment]
Hi @liufei11111 there's no magic there, you can check the boxes here https://atlas.hashicorp.com/capgemini/boxes/apollo
Vagrant box as well as ami, droplets or any other image for any other cloud are generated via Packer
https://github.com/Capgemini/Apollo/tree/master/packer

You might want to have a look at the docs https://github.com/Capgemini/Apollo/blob/master/docs/packer.md

**Comment by liufei11111** [comment]
Oh, sorry, I didn't read deep enough. It looks that everything is based on Ubuntu now. Are you going to support something like Debian in the future? I don't know if it is as simple as figure out the debian version of "Apollo/packer/scripts/ubuntu/install_docker.sh". If it is, I suggest that a support for debian is added because it is really used more heavily in Production. Thanks.

**Comment by wallies** [comment]
@liufei11111 no plans to support debian in the future. There are plans to move to systemd so we can migrate to CoreOS.
