### ISSUE TITLE
Initialization failed on Vagrant

### ISSUE THREAD

**Issue by liufei11111** [Capgemini/Apollo#548]
Hi,
I am running a test run for Apollo and my dependencies are here:

Viriual box Version 5.0.6 r103037
Vagrant 1.7.4
Python 2.7.10
"
Turn up the cluster as below will give me an error message:
export APOLLO_PROVIDER=vagrant
/bin/bash bootstrap/apollo-launch.sh"

"TASK: [dnsmasq | run dnsmasq container] *************************************** 
failed: [master1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)
failed: [master3] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)
failed: [master2] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)
failed: [slave1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/feiliu/site.retry

master1                    : ok=25   changed=18   unreachable=0    failed=1   
master2                    : ok=25   changed=18   unreachable=0    failed=1   
master3                    : ok=25   changed=18   unreachable=0    failed=1   
slave1                     : ok=25   changed=18   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again."

If I run standalone mode, it will give me another message:

"
TASK: [dnsmasq | run dnsmasq container] *************************************** 
failed: [master1] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/feiliu/site.retry

master1                    : ok=25   changed=18   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
"

It looks that vagrant changes the way ssh to the box works.

**Comment by enxebre** [comment]
Hi @liufei11111 the vagrant box is probably not up to date with latest changes in code resulting on unexpected issues. We'll be rebuilding the vagrant box and fixing potential issues with vagrant environment during this week. In the meanwhile you can always rebuild the image by yourself as per https://github.com/Capgemini/Apollo/blob/master/docs/packer.md#building-the-packer-images
Thanks!

**Comment by liufei11111** [comment]
That's great! I will try it latter today. Thanks.

**Comment by ravbaba** [comment]
Hi @liufei11111, I built a new vagrant box yesterday evening so it should be fine now.

**Comment by broomyocymru** [comment]
I was getting the same problem too. Can confirm with the latest vagrant box its fixed it and everything is up and running.

**Comment by wallies** [comment]
I am going to close out this issue then. Cheers everyone.
