### ISSUE TITLE
Marathon apps are not running on vagrant provider

### ISSUE THREAD

**Issue by ravbaba** [Capgemini/Apollo#564]
When I run apollo with a vagrant provider, Marathon apps don't start up. I checked docker logs of all the apps which I run with dcos-cli and all of them have the same errror:

```URL [http://127.0.0.1:8080/v2/info] is unreachable: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v2/info (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9d0d664890>: Failed to establish a new connection: [Errno 111] Connection refused',))```

it looks like the host gets wrong ip address 127.0.0.1 instead of 172.31.1.11 etc. I might be wrong, it is only my assumption :)

**Comment by tayzlor** [comment]
Should be fixed by https://github.com/Capgemini/Apollo/pull/569
