### ISSUE TITLE
Handle DOCKER_HOST variable better in coreOS

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#581]
In ubuntu we used DOCKER_HOST to point to the weave socket so that containers would use and start up via the weave socket. 

We need to review this and see whether we need to build it into the coreOS approach using systemd

**Comment by enxebre** [comment]
Related to https://github.com/Capgemini/Apollo/issues/514 We might just want to reconsider the current approach

**Comment by enxebre** [comment]
The Weave Net plugin runs automatically when you weave launch so we should be able to just use ```--net=weave``` for now

**Comment by enxebre** [comment]
Closing this as we dont need this variable on the playbook as most infrastructure containres run on host network or the weave socket is passed as a volume from systemd script.
Services deployed by marathon automatically goes through weave via mesos config.
This should be handle via libnet plugins net and --net parameter for coreOS beta/docker 1.9
