### ISSUE TITLE
Use Nomad instead of Mesos

### ISSUE THREAD

**Issue by sheerun** [Capgemini/Apollo#589]
Hey,

Apollo is already pretty integrated with Hashicorp products (Vault, Terraform, Consul).

How about also using Nomad instead of Mesos?

**Comment by tayzlor** [comment]
Hi @sheerun thanks for the post. We don't have any immediate plans to integrate nomad, but if someone was willing to work on this we'd welcome the discussion or a pull request.

**Comment by tayzlor** [comment]
Closing. Feel free to re-open if you need more support or open a PR if you'd like to see it included.
