### ISSUE TITLE
traefik hot reload not working because weave SDN isnt configured

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#596]
Because the traefik container cannot be communicated with from the marathon container because it isn't yet on the weave bridge.

its curretly resolving to a docker bridge IP which isn't available across hosts.

Related https://github.com/Capgemini/Apollo/issues/581

**Comment by enxebre** [comment]
This should be fine now
https://github.com/Capgemini/Apollo/pull/610
https://github.com/Capgemini/Apollo/pull/608
https://github.com/Capgemini/Apollo/pull/607
