### ISSUE TITLE
Solution for container to container communication dns resolution

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#600]
As we got traefik in and removed registrator now we can handle the discovery for the "front-end" apps by mapping the host ip and host port on traeffik but the internal apps deployed trough marathon (with label traefik.enable=false) won't register on consul its SDN ip anymore so we need to put a solution in place for container to container communication.
We could consider mesos-dns / docker-overlay and docke-dns / weave dns

**Comment by wallies** [comment]
weave dns ties us to much to weave. mesos-dns is used in a lot of places but docker is the core of the platform and what we are trying to solve, so Im with docker-overlay or docker-dns

**Comment by enxebre** [comment]
For now we restore registrator and rely on consul as dns server.
Looking at docker overlay/consul-mesos for CoreOS beta with docker 1.9
