### ISSUE TITLE
Vagrant timeout on "TASK: [consul | wait for leader]"

### ISSUE THREAD

**Issue by broomyocymru** [Capgemini/Apollo#628]
Launching apollo with Vagrant keeps hanging waiting for consul leader election.

**Comment by tayzlor** [comment]
@broomyocymru Have you tried the devel branch? This is the one we are mainline developing on and it is based on CoreOS. We will likely merge this into master shortly. Give it a spin on devel and let us know if you face the same issue (I don't have this problem on devel branch)

**Comment by broomyocymru** [comment]
Devel branch worked. I did get an issue with DD_API_KEY not being set so I changed datadog_enabled to false. Maybe it should be disabled by default?

**Comment by tayzlor** [comment]
It should be disabled by default yep - feel free to send in a PR against devel branch if you can. 

Thanks,
Graham.
