### ISSUE TITLE
Use public networking for digitalocean

### ISSUE THREAD

**Issue by sheerun** [Capgemini/Apollo#651]
"Private networking" on digital ocean isn't private at all:
http://incoherency.co.uk/blog/stories/digital-ocean-private-network.html

So we might as well use public networking and allow masters to span across datacenters, forexample 3 masters in nyc1, nyc2, and nyc3. Currently you can't do it because private shared networking cannot reach across datacenters even in the same region.

**Comment by tayzlor** [comment]
@sheerun agreed. thanks for the heads up - we'll push a fix into devel for that shortly

**Comment by tayzlor** [comment]
Closing via #654
