### ISSUE TITLE
Have mesos span multiple availability zones

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#66]
![screen shot 2015-04-10 at 09 46 37](https://cloud.githubusercontent.com/assets/1681896/7084576/a7000cc0-df66-11e4-85df-b746410f4a17.png)

We should be able to achieve something like the above - having 2 masters in one AZ and another in a second AZ (providing higher availability)

**Comment by keithchambers** [comment]
To improve availability you'd need to spread ZK and Consul across 3 AZs in a single region.

**Comment by tayzlor** [comment]
![mesos-ha-architecture](https://cloud.githubusercontent.com/assets/1681896/8307068/7f1c6388-19b4-11e5-900f-cc99de1f779e.png)

**Comment by keithchambers** [comment]
This should work fine.

**Comment by enxebre** [comment]
Closing as https://github.com/Capgemini/Apollo/pull/385 got in.
