### ISSUE TITLE
Why is consul started before weave

### ISSUE THREAD

**Issue by sheerun** [Capgemini/Apollo#663]
Hey

Just wondering why you start consul before weave and then restart it instead just starting weave before consul? Any reason?

**Comment by sheerun** [comment]
Also, why you use public ips for consul instead of weave network

**Comment by enxebre** [comment]
Hey @sheerun correct, consul should be running after so it runs on the weave network so it can run health checks on weave net.

**Comment by enxebre** [comment]
https://github.com/Capgemini/Apollo/pull/665

**Comment by tayzlor** [comment]
Closing via #665
