### ISSUE TITLE
Discuss / brainstorm approach to Monitoring and alerting

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#67]
We need to be able to monitor the entire stack. Some things we need to monitor - 

- Node level monitoring (CPU/Mem/Disk etc...) - Some of this can be achieved through consul / atlas but we still need alerting
- Docker container monitoring
- Mesos framework monitoring (maybe http://www.antonlindstrom.com/2015/02/24/monitoring-mesos-tasks-with-prometheus.html), Mesos also has its stats endpoint.
- Alerts on monitors - alerting roll-up - types of alerts
- Service level monitoring (related to docker monitoring)

**Comment by keithchambers** [comment]
For Consul based alerting @armon is a fan of https://github.com/AcalephStorage/consul-alerts.  Atlas will have an integration is PagerDuty shortly.

**Comment by wallies** [comment]
I really like prometheus. It has this for consul https://github.com/prometheus/consul_exporter

**Comment by keithchambers** [comment]
For microservices-infrastructure we want to decorate all logs and metrics with contextual metadata e.g., container_datacenter, container_host, container_name/id, container_version.

This should make it much simpler for app operators to diagnose issues across a multi-dc shared container runtime.

I'm interested in hearing your thoughts ... :-)

**Comment by keithchambers** [comment]
@wallies kk -- are you guys using Prometheus in production? Is it scaling well and easy to operate?  I'm pretty lazy. ;-)

I'll spend some time hands on with it this week.

**Comment by wallies** [comment]
@keithchambers we arent using it in Production. I think it is based on Influxdb, which can scale really well for different datacenters and zones if you start to shard.

**Comment by tayzlor** [comment]
Closing this as we started to intregate prometheus via https://github.com/Capgemini/Apollo/pull/526
