### ISSUE TITLE
Unable to bootstrap on aws

### ISSUE THREAD

**Issue by joe1chen** [Capgemini/Apollo#678]
I have set ```APOLLO_PROVIDER=aws``` and all the other environment variables, but when I run ```/bin/bash bootstrap/apollo-launch.sh``` it results in an error.

Output:
```
/bin/bash bootstrap/apollo-launch.sh
bootstrap/apollo-launch.sh: line 10: bootstrap/../bootstrap/../bootstrap/aws/util.sh: No such file or directory
```

Looks like the aws files got moved around?  There is now a ```aws/public-cloud/util.sh``` and ```aws/private-cloud/util.sh```.  How can I fix the error?

**Comment by wallies** [comment]
@joe1chen if you set APOLLO_PROVIDER=aws/public-cloud or APOLLO_PROVIDER=aws/private-cloud it should work

**Comment by joe1chen** [comment]
Thanks, the docs need to be updated.

**Comment by tayzlor** [comment]
@joe1chen yes - they do - they're a bit out of date since we merged some PRs to move to CoreOS. Please feel free to send in a PR to update the docs if you can!

**Comment by joe1chen** [comment]
@tayzlor Will definitely send a PR once I get everything working.  I'm now blocked on issue #679.
