### ISSUE TITLE
Zookeeper setup is failing with Ansible 2.0

### ISSUE THREAD

**Issue by joe1chen** [Capgemini/Apollo#690]
After the upgrade to Ansible 2.0, all references to ```ansible_ssh_host``` were replaced with ```ansible_host```.  Unfortunately, inside of ```hostvars[host]``` the key is still called ```ansible_ssh_host```.  I've filed a bug with Ansible (https://github.com/ansible/ansible/issues/15286).

Currently, when installing the master version of Apollo using Ansible 2.0.1.0, you will run into this error:
```
TASK [zookeeper : Create zookeeper config files] *******************************
failed: [apollo-mesos-master-1] => (item={u'dest': u'/etc/zookeeper/conf/zoo.cfg', u'src': u'zoo.cfg.j2'}) => {"failed": true, "item": {"dest": "/etc/zookeeper/conf/zoo.cfg", "src": "zoo.cfg.j2"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_host'"}
```

**Comment by joe1chen** [comment]
I'm surprised not more people have run into this issue.  By the way, I am running Ansible from OS X 10.11.4.

**Comment by wallies** [comment]
@joe1chen i havent seen this issue and im running the same setup, strange but thanks once again.

**Comment by joe1chen** [comment]
Closing this out since it seems like an issue with ansible on localhost.
