### ISSUE TITLE
Create a terraform plan for Google cloud

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#95]
Similar to AWS / Digitalocean but for Google. Depends on #13

**Comment by wallies** [comment]
might want to use this as an example https://github.com/ContainerSolutions/terraform-mesos

**Comment by enxebre** [comment]
This is closed by https://github.com/Capgemini/Apollo/commit/6cf1736eeb56559d6bf7e4e90fea16f1f7c14424
Using https://github.com/Capgemini/terraform.py for the inventory.
There is also some work here https://github.com/Capgemini/apollo-inventory for a Go version
